# DO NOT USE IN PRODUCTION

services:
   app:
     build:
       context: .
       dockerfile: backend.Dockerfile
     command: python manage.py runserver 0.0.0.0:8000
     restart: unless-stopped
     depends_on:
       - db
     volumes:
       - $PWD/ctf_platform_backend:/opt/ctf_platform_backend/ctf_platform_backend
       - ./django-static:/opt/ctf-platform-backend/static-root
       - ./media-static:/opt/ctf-platform-backend/media-root
     ports:
       - 8000:8000
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_HOST: postgres
       POSTGRES_PORT: 5432
       POSTGRES_DB: postgres
       ALLOWED_HOSTS: "localhost"
       CORS_ALLOWED_ORIGINS: "http://localhost:5173"
       CSRF_TRUSTED_ORIGINS: "http://localhost:5173"
       DEBUG: "True"
       SECRET_KEY: "secret"

   db:
     image: postgres:13
     restart: unless-stopped
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=postgres
     volumes:
       - ./postgres-data:/var/lib/postgresql/data
     ports:
       - 5432:5432