# DO NOT USE IN PRODUCTION

services:
   app:
     build:
       context: .
       dockerfile: Dockerfile
     command: poetry run python manage.py runserver 0.0.0.0:8000
     restart: unless-stopped
     depends_on:
       - db
     volumes:
       - $PWD/ctf_platform_backend:/opt/ctf_platform_backend/ctf_platform_backend
       - $PWD/client:/opt/ctf-platform-backend/client
     ports:
       - 8000:8000
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_HOST: postgres
       POSTGRES_PORT: 5432
       POSTGRES_DB: postgres

   db:
     image: postgres:13
     restart: unless-stopped
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=postgres
     volumes:
       - ./postgres-data:/var/lib/postgresql/data
     ports:
       - 5432:5432