name: build-and-push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push platform backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend.Dockerfile
          push: true
          tags: ghcr.io/kolo-cybersec-wat/ctf-platform-backend:latest

      - name: Build and push platform frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend.Dockerfile
          push: true
          tags: ghcr.io/kolo-cybersec-wat/ctf-platform-frontend:latest